### ISSUE TITLE
Doesn't works with Magisk Manager

### ISSUE THREAD

**Issue by DawnSpark7** [Aspire0ne/Google-Assistant-enabler#6]
Throws an error saying its not an magisk module

**Comment by AspireOne** [comment]
I just tried it, it works. You either have an ancient version of magisk manager, or you didn't download the module from the google drive link.

Download the zip from google drive -> flash.

**Comment by DawnSpark7** [comment]
Well, I've Magisk version 20.4 and Magisk Manager version 8.0.2 🤔

**Comment by DawnSpark7** [comment]
_Download the zip from google drive -> flash_ I tried this right now. It still fails.

**Comment by AspireOne** [comment]
That's impossible, there must be something you're doing differently. The only thing I can think of is that whatever you're downloading the module through is zipping it - so you would have a zip, and only in that zip would be the real zip (module). Did you check if the zip directly contains the files shown here on github?

**Comment by DawnSpark7** [comment]
Yeah I had done that. Just in case you need more info then here it is.

Phone : Mi A2
ROM : Pixel Experience Plus (Android 10)
Magisk : 20.4
Magisk Manager : 8.0.2
Modules : Magisk Hide Props

Anyways, I got it working through an XDA Guide. Thanks for your brilliant work 💯
